# Generated by Django 5.0.3 on 2024-03-29 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_description', models.CharField(max_length=255)),
                ('news_image', models.ImageField(upload_to='news')),
                ('news_content', models.TextField()),
                ('news_pub_date', models.DateTimeField(auto_now_add=True)),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_news.categories')),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
